name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build the project
        run: |
          cd client
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify-cli@v2
        with:
          netlify_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_path: ./client/dist
