name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set the Node.js version you are using

      - name: Navigate to client directory
        run: cd client # Change directory to client

      - name: Install dependencies
        run: npm install # Install dependencies inside client folder

      - name: Build React app
        run: npm run build # Run the build command inside client folder

      - name: Deploy to GitHub Pages
        run: npm run deploy # Deploy using gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
