name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use the appropriate Node.js version

      - name: Install, build, and deploy
        run: |
          cd client
          npm install
          npm run build
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
